services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wafer_inspection
    ports:
      - "5555:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    volumes:
      - ./docker/cbdata:/opt/cloudbeaver/workspace
    depends_on:
      - postgres
