classes:
- name: pad
  id: 1
  color:
  - 0
  - 120
  - 255
  enabled: true
- name: probemark
  id: 2
  color:
  - 0
  - 255
  - 0
  enabled: true
- name: grain
  id: 3
  color:
  - 255
  - 0
  - 0
  enabled: false
data:
  raw: data/1_raw
  processed_unet: data/2_processed_unet
  processed_yolo: data/3_processed_yolo
  test: data/test
models:
  unet: models/2class/weights/unet_pytorch_2class.pth
  unet_keras: models/2class/weights/unet_keras_2class.keras
  resnet_unet: models/2class/weights/resnet34_unet_2class.pth
  yolo_pretrained: models/pretrained/yolov8n-seg.pt
  yolo_best: models/2class/weights/yolov8n_seg_2class.pt
training:
  epochs: 200
  batch_size: 64
  learning_rate: 0.0001
  image_size:
  - 256
  - 256
